apiVersion: v1
kind: Pod
metadata:
  name: test-2-service
spec:
  containers:
  - args:
    - -c
    - while true; do curl http://ec2-54-89-164-120.compute-1.amazonaws.com; sleep
      10;done
    command:
    - /bin/bash
    image: ubuntu
    name: ubuntu-container
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: '0.1'
        memory: 1Gi
    volumeMounts:
    - mountPath: /var
      name: shared-data
  restartPolicy: Never
  volumes:
  - emptyDir: {}
    name: shared-data
